nginx:
  image: nginx
  stdin_open: true
  tty: true
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
balancer:
  image: rancher/lb-service-haproxy:v0.5.9
  ports:
  - 80:80/tcp
  labels:
    io.rancher.container.agent.role: environmentAdmin
    io.rancher.container.create_agent: 'true'
