.catalog:
  name: "Product"
  version: "1.14.2"
  description: "Product 1.14.2"
  uuid: myproduct
  minimum_rancher_version: v0.44.0
nginx:
  scale: 1
  start_on_create: true
balancer:
  scale: 1
  start_on_create: true
  lb_config:
    certs: []
    port_rules:
    - path: ''
      priority: 1
      protocol: http
      service: nginxcontainer
      source_port: 90
      target_port: 80
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    interval: 2000
  metadata:
    prd_version: "1.14.2"