.catalog:
  name: "Health check"
  version: "2.0.0"
  description: "Services"
healthcheckfail:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    request_line: 'GET "/404" "HTTP/1.1\r\nHost: blah.com"'
    healthy_threshold: 2
    response_timeout: 2000
    reinitializing_timeout: 50000
healthcheckpass:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    request_line: 'GET "/" "HTTP/1.1\r\nHost: blah.com"'
    healthy_threshold: 2
    response_timeout: 2000
    reinitializing_timeout: 50000
